[package]
name = "futility"
version = "0.1.0"
authors = ["jharrymoore <jharrymoore@btinternet.com>"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
crossbeam = "0.8.2"
crossterm = "0.26.1"
notify = "6.1.1"
ratatui = "0.24.0"
